DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS spa CASCADE;

CREATE TABLE users (
	id SERIAL PRIMARY KEY,
	email VARCHAR NOT NULL UNIQUE,
	password_digest VARCHAR NOT NULL
);

CREATE TABLE spa (
	id SERIAL PRIMARY KEY,
	name VARCHAR NOT NULL,
	address VARCHAR NOT NULL 
);